import React, { useState } from 'react';
import { Upload, Image, Eye, Download, Zap, FileImage } from 'lucide-react';

const Otolith = () => {
  const [dragOver, setDragOver] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [analysisResults, setAnalysisResults] = useState(null);
  const fileInputRef = React.useRef(null);

  const sampleResults = {
    species: "Atlantic Cod",
    confidence: 92,
    age: "4-5 years",
    growth_rate: "Normal",
    environmental_conditions: "Optimal"
  };

  const sampleGallery = [
    { id: 1, name: "otolith_001.jpg", species: "Atlantic Cod", age: "3 years", analyzed: true },
    { id: 2, name: "otolith_002.jpg", species: "Bluefin Tuna", age: "7 years", analyzed: true },
    { id: 3, name: "otolith_003.jpg", species: "Atlantic Salmon", age: "2 years", analyzed: false },
    { id: 4, name: "otolith_004.jpg", species: "Mackerel", age: "4 years", analyzed: true },
  ];

  const handleDragOver = (e) => {
    e.preventDefault();
    setDragOver(true);
  };

  const handleDragLeave = () => {
    setDragOver(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    const files = Array.from(e.dataTransfer.files);
    setUploadedFiles(prev => [...prev, ...files]);
  };

  const handleAnalyze = () => {
    setAnalysisResults(sampleResults);
  };

  const handleChooseFiles = () => {
    fileInputRef.current?.click();
  };

  const handleFileSelect = (e) => {
    const files = Array.from(e.target.files);
    setUploadedFiles(prev => [...prev, ...files]);
  };

  const handleDownloadReport = () => {
    const reportContent = `Otolith Analysis Report

Analysis Results:
- Species: ${analysisResults.species}
- Confidence: ${analysisResults.confidence}%
- Estimated Age: ${analysisResults.age}
- Growth Rate: ${analysisResults.growth_rate}
- Environmental Conditions: ${analysisResults.environmental_conditions}

Generated by Shark Marine Platform
Date: ${new Date().toLocaleDateString()}`;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'otolith-analysis-report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="py-12 px-6 min-h-screen bg-[#F8F9FB]">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-semibold text-[#30345E] mb-4">Shark Otolith Analysis</h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Upload otolith images for AI-powered species identification and age estimation
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 mb-12">
          {/* Upload Section */}
          <div className="space-y-6">
            <h2 className="text-2xl font-semibold text-[#30345E]">Upload Otolith Images</h2>
            
            <div
              className={`bg-white rounded-2xl border-2 border-dashed p-8 text-center transition-all duration-300 ${
                dragOver ? 'border-[#30345E] bg-[#30345E]/5' : 'border-gray-200 hover:border-[#30345E]'
              }`}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
            >
              <Upload className="w-12 h-12 text-[#30345E] mx-auto mb-4" />
              <h3 className="text-lg font-medium text-[#30345E] mb-2">Drop your otolith images here</h3>
              <p className="text-gray-600 mb-4">or click to browse files</p>
              <button 
                onClick={handleChooseFiles}
                className="bg-[#30345E] text-white px-6 py-2 rounded-md hover:scale-105 transition-all duration-200"
              >
                Choose Files
              </button>
              <input
                ref={fileInputRef}
                type="file"
                multiple
                accept="image/*"
                onChange={handleFileSelect}
                className="hidden"
              />
              <p className="text-sm text-gray-500 mt-2">Supports JPG, PNG, TIFF files up to 10MB</p>
            </div>

            {/* Uploaded Files */}
            {uploadedFiles.length > 0 && (
              <div className="bg-white rounded-2xl p-6 shadow-sm">
                <h3 className="text-lg font-semibold text-[#30345E] mb-4">Uploaded Files</h3>
                <div className="space-y-3">
                  {uploadedFiles.map((file, index) => (
                    <div key={index} className="flex items-center justify-between p-3 bg-[#F8F9FB] rounded-lg">
                      <div className="flex items-center space-x-3">
                        <FileImage className="w-5 h-5 text-[#30345E]" />
                        <span className="text-sm font-medium text-[#1A1A1A]">{file.name}</span>
                      </div>
                      <button
                        onClick={handleAnalyze}
                        className="bg-[#30345E] text-white px-4 py-2 rounded-md text-sm hover:scale-105 transition-all duration-200 flex items-center space-x-2"
                      >
                        <Zap className="w-4 h-4" />
                        <span>Analyze</span>
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Analysis Results */}
          <div className="space-y-6">
            <h2 className="text-2xl font-semibold text-[#30345E]">Analysis Results</h2>
            
            {analysisResults ? (
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-[#30345E]">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-[#30345E]">Species Identification</h3>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-green-400 rounded-full"></div>
                    <span className="text-sm text-green-600 font-medium">Analysis Complete</span>
                  </div>
                </div>
                
                <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-600">Species</p>
                      <p className="text-lg font-semibold text-[#30345E]">{analysisResults.species}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Confidence</p>
                      <div className="flex items-center space-x-2">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-green-400 h-2 rounded-full transition-all duration-500"
                            style={{ width: `${analysisResults.confidence}%` }}
                          ></div>
                        </div>
                        <span className="text-sm font-semibold text-[#30345E]">{analysisResults.confidence}%</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-600">Estimated Age</p>
                      <p className="text-lg font-semibold text-[#30345E]">{analysisResults.age}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Growth Rate</p>
                      <p className="text-lg font-semibold text-[#30345E]">{analysisResults.growth_rate}</p>
                    </div>
                  </div>
                  
                  <div>
                    <p className="text-sm text-gray-600">Environmental Conditions</p>
                    <p className="text-lg font-semibold text-[#30345E]">{analysisResults.environmental_conditions}</p>
                  </div>
                  
                  <button 
                    onClick={handleDownloadReport}
                    className="w-full bg-[#30345E] text-white py-3 rounded-lg hover:scale-105 transition-all duration-200 flex items-center justify-center space-x-2"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download Report</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-2xl p-8 shadow-sm text-center">
                <Image className="w-12 h-12 text-gray-400 mx-auto mb-4" />
                <p className="text-gray-500">Upload otolith images to see analysis results</p>
              </div>
            )}
          </div>
        </div>

        {/* Otolith Gallery */}
        <div className="bg-white rounded-2xl p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-[#30345E] mb-6">Otolith Gallery</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {sampleGallery.map((item) => (
              <div key={item.id} className="bg-[#F8F9FB] rounded-xl p-4 hover:shadow-md transition-all duration-200">
                <div className="h-32 bg-gradient-to-br from-blue-100 to-blue-200 rounded-lg mb-3 flex items-center justify-center">
                  <Image className="w-8 h-8 text-[#30345E]" />
                </div>
                <h3 className="font-medium text-[#30345E] mb-1">{item.name}</h3>
                <p className="text-sm text-gray-600">{item.species}</p>
                <p className="text-sm text-gray-600">Age: {item.age}</p>
                <div className="flex items-center justify-between mt-3">
                  <span className={`text-xs px-2 py-1 rounded-full ${
                    item.analyzed ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                  }`}>
                    {item.analyzed ? 'Analyzed' : 'Pending'}
                  </span>
                  <button className="text-[#30345E] hover:scale-110 transition-transform">
                    <Eye className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Otolith;